#!/usr/bin/env bash
#World wide web
dig_this () 
{
    result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $result" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
    declare -a arg=("www" "lb-01" "web-01" "web-02")
    for x in "${arg[@]}"
    do
        dig_this "$1" "$x"
done
elif [ "$#" == 2 ]
then
  dig_this "$1" "$2"
fi
