#!/usr/bin/env bash
# Configure your Nginx server so that 
sudo apt-get update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
