#!/usr/bin/env bash
# Configure your Nginx server so that 
sudo nginx -t
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx reload
service nginx restart
