#!/usr/bin/env bash
# Installs and configure load balancer

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*
echo "
frontend lb
        bind *:80
        mode http
        default_backend servers
        
backend servers
        mode http
        balance roundrobin
        server web-01 34.73.28.199:80 check
        server web-02 35.229.73.92:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
