#!/usr/bin/env bash
# Configu
apt-get -y update
apt-get install haproxy
printf "\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend be_main\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 525-web-01 34.73.28.199 tfo\n\tserver 525-web-02 35.229.73.92 tfo" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
