#!/usr/bin/env bash
# Configure load balancer
apt-get -y update
apt-get -y install haproxy
printf "\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend rebe_main\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 525-web-01 34.73.28.199 \n\tserver 525-web-02 35.229.73.92" >> /etc/haproxy/haproxy.cfg
service haproxy restart
