#!/usr/bin/env bash
#script that displays Holberton School 10 times, but for the 9th
i=1
while [ $i -lt 11 ]; do
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
        echo "Holberton School"
    ((i++))
done
