#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and: bad luck
foo=1
while [ $foo -le 10 ]; do
      if [ $foo -eq 4 ]; then
      	 echo "bad luck"
      elif [ $foo -eq 8 ]; then
      	   echo "good luck"
      else
	echo "Holberton School"
      fi
      ((foo++))
done
