#!/usr/bin/env bash
# Script to display numbers from 1-20 in 4th iteration "bad luck from China", " bad luck from Japan"
i=1
while [ $i -lt 21 ]; do
      echo $i
      case $i in
      	   4) echo "bad luck from China"
	      ;;
	   9) echo "bad luck from Japan"
	      ;;
	   17) echo "bad luck from Italy"
	       ;;
      esac
      ((i++))
done
