#!/usr/bin/env bash
# run as nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -u nginx nginx -c /etc/nginx/nginx.conf
chmod -R 777 /etc/nginx/
