#!/usr/bin/env bash
# run as nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod -R a+rwx /etc/nginx/
service nginx restart
